### ISSUE TITLE
Add sponsors content type

### ISSUE THREAD

**Issue by WhiteHoodHacker** [sigpwny/sigpwny.com#8]
This would allow us to easily display current and past sponsors of SIGPwny. We can also build relations between sponsors and events.

Current working format:
```
name: "Sponsor Name"
image:
  path: "./image.png"
  alt: "Sponsor image"
weight: 0
sponsoring_semesters: ["fa2022", "sp2023"] # "yearly" sponsors
sponsoring_events: ["uiuctf/2022", "fallctf/2023"] # event sponsors
```

Additional fields could include sponsor-provided materials, such as recruitment links.

Ideally, we can work on a format that combines both `sponsoring_semesters` and `sponsoring_events` fields. We should also be able to create a GraphQL relation between `Event` and `Sponsor` content types so that way sponsors can be displayed on `Event` pages. However, sponsor-provided materials and weight may change between events, so this may not be the best solution.
